config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cashbacks#home'

  get '/nz', to: 'cashbacks#home'
  get '/cashback_promotions', to: 'cashbacks#promotions'
  get '/cashback_payments_and_distribution', to: 'cashbacks#cashback_payments_and_distribution'
  get '/loyalty_programs', to: 'cashbacks#loyalty_programs'
  get '/competitions_sweepstakes_and_games', to: 'cashbacks#competitions_sweepstakes_and_games'
  get '/promotion_management', to: 'cashbacks#promotion_management'
  get '/gift_with_purchase', to: 'cashbacks#gift_with_purchase'
  get '/eftpos_cash_back_cards', to: 'cashbacks#eftpos_cash_back_cards'
  get '/about_us', to: 'cashbacks#about_us'
  get '/register', to: 'cashbacks#register'
  post '/register_cashback', to: 'cashbacks#register_cashback'
  get '/contact', to: 'cashbacks#contact'
  post '/contact_cashback', to: 'cashbacks#contact_cashback'

  get '/prologic', to: 'prologic#home'
  post '/contact_prologic', to: 'prologic#contact_prologic'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def cashback_contents
    @original_url = request.original_url
    @is_au_site = true

    if @original_url.include?(ENV['CASHBACK_NZ_URL']) || request.query_parameters['site'] === "mycashback"
      @is_au_site = false

      @site_name = ENV['CASHBACK_NZ_SITE']
      @contact_email = ENV['CASHBACK_NZ_EMAIL']

      @logo = "cashbacks/images/nz-logo.png"
      @logo_class = "nz-logo"
      @phone = "tel:0800669487"
      @phone_display = " 0800 669 487"
      @address = {line_1: "PO Box 147167", line_2: "Ponsonby", line_3: "Auckland, 1144"}

      @facebook_url = "https://www.facebook.com/Mycashbackconz-822899344511890/"
      @twitter_url = "https://twitter.com/MyCashBackconz"
      @linkedin_url = "https://www.linkedin.com/company-beta/18047407/"

    else
      @site_name = ENV['CASHBACK_AU_SITE']
      @contact_email = ENV['CASHBACK_AU_EMAIL']

      @logo = "cashbacks/images/au-logo.png"
      @logo_class = "au-logo"
      @phone = "tel:1300669487"
      @phone_display = " 1 300 669 487"
      @address = {line_1: "PO BOX 6331", line_2: "Alexandria, NSW 2015", line_3: "Australia"}

      @facebook_url = "https://www.facebook.com/CashBackcomau-441603355903263/"
      @twitter_url = "https://twitter.com/CashBackcomau"
      @linkedin_url = "https://www.linkedin.com/company-beta/3007416/"
    end
  end

  def is_matching_url url, site
    request.original_url.include?(url) || request.query_parameters['site'] === site
  end
end

app/controllers/cashbacks_controller.rb
class CashbacksController < ApplicationController
  layout "cashbacks"
  before_action :cashback_contents

  def home
  end

  def promotions
  end

  def cashback_payments_and_distribution
  end

  def loyalty_programs
  end

  def competitions_sweepstakes_and_games
  end

  def promotion_management
  end

  def gift_with_purchase
  end

  def eftpos_cash_back_cards
  end

  def about_us
  end

  def register
  end

  def register_cashback
    RegisterMailer.register_cashback(@contact_email, params[:name], params[:email]).deliver_later
    redirect_to '/'
  end

  def contact
  end

  def contact_cashback
    ContactMailer.contact_cashback(@contact_email, params[:name], params[:email], params[:message]).deliver_later
    redirect_to '/'
  end
end

app/controllers/prologic_controller.rb
class PrologicController < ApplicationController
  layout "pro_logic"

  def home
  end

  def contact_prologic
    ContactMailer.contact_prologic(ENV['PROLOGIC_EMAIL'], params[:name], params[:email], params[:message]).deliver_later
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cashbacks/about_us.html.erb
<%= render partial: "components/header", locals: { current_menu_parent: "", menu_home_class: "", menu_cashback_promotions_class: "", menu_cashback_payments_and_distribution_class: "",menu_loyalty_programs_class: "",
                                                    menu_competitions_sweepstakes_and_games_class: "", menu_promotion_management_class: "", menu_gift_with_purchase_class: "",
                                                    menu_eftpos_cash_back_cards_class: "", menu_about_us_class: "current-menu-item", menu_register_class: "", menu_contact_class: ""} %>

<!-- Page Banner -->
<section id="page-banner-container" class="fixed-bg" style="background: transparent url(cashbacks/images/about-banner.jpg) no-repeat center center;">
  <article id="page-banner">
    <h1>Australia and New Zealand’s cashback promotion specialists</h1>

    <!-- Center -->
    <div class="center">
      <p>Since 2004, <%= @site_name %> has led the way in cashback and loyalty program marketing in Australia and New Zealand, providing fun and rewarding experiences for consumers while helping drive growth for our clients.</p>
      <p>In this time, we have run campaigns for some of the world’s most visible brands, helping them to:</p>
      <ul>
        <li>Boost profits</li>
        <li>Gain market share</li>
        <li>Raise product awareness and brand visibility</li>
        <li>Increase sales</li>
      </ul>
    </div>

    <!-- Clients -->
    <div class="clients">
      <img src="cashbacks/images/canon-logo-white.jpg" />
      <img src="cashbacks/images/nikon-logo-white.jpg" />
      <img src="cashbacks/images/garmin-logo-white.jpg" />
      <img src="cashbacks/images/adobe-logo-white.jpg" />
      <img src="cashbacks/images/makita-logo-white.jpg" />
      <img src="cashbacks/images/imation-logo-white.jpg" />
      <img src="cashbacks/images/fujifilm-logo-white.jpg" />
      <img src="cashbacks/images/netgear-logo-white.jpg" />
    </div>

    <!-- Center -->
    <div class="center">
      <p>By providing end-to-end solutions, we can also offer a cost-effective way to expand your marketing activity. Using our years of experience and detailed sector knowledge, we have all the tools required to make sure delivery is as smooth as possible.</p>
      <p><%= @site_name %> is a division of Pro-Logic International, a promotional management company operating across Australia and New Zealand.</p>
    </div>
  </article>
</section>


<!-- Wrapper -->
<div id="wrapper">
  <%= render partial: "components/contact_us" %>
  <%= render partial: "components/footer", locals: {current_footer_parent: "", footer_home_class: "", footer_cashback_promotions_class: "", footer_cashback_payments_and_distribution_class: "",footer_loyalty_programs_class: "",
                                                      footer_competitions_sweepstakes_and_games_class: "", footer_promotion_management_class: "", footer_gift_with_purchase_class: "",
                                                      footer_eftpos_cash_back_cards_class: "", footer_about_us_class: "current-menu-item", footer_register_class: "", footer_contact_class: ""} %>
</div>

app/views/cashbacks/cashback_payments_and_distribution.html.erb
<%= render partial: "components/header", locals: { current_menu_parent: "current-menu-parent", menu_home_class: "", menu_cashback_promotions_class: "", menu_cashback_payments_and_distribution_class: "current-menu-item", menu_loyalty_programs_class: "",
                                                    menu_competitions_sweepstakes_and_games_class: "", menu_promotion_management_class: "", menu_gift_with_purchase_class: "",
                                                    menu_eftpos_cash_back_cards_class: "", menu_about_us_class: "", menu_register_class: "", menu_contact_class: ""} %>

<!-- Page Banner -->
<section id="page-banner-container" style="background: transparent url(cashbacks/images/currency-banner.jpg) no-repeat center center;">
  <article id="page-banner">
    <h1>Cashback payments and distribution</h1>
    <h2>Using the latest technology to reward your customers</h2>
  </article>
</section>

<!-- Wrapper -->
<div id="wrapper">
  <!-- Content -->
  <section class="container">
    <article class="content no-padding">
      <!-- Column Left -->
      <div class="column-left column">
        <img class="alignright" src="cashbacks/images/currency-image-1.png" />
      </div>

      <!-- Column Right -->
      <div class="column-right column">
        <h2>EFT, Branded Eftpos Cards and even Cheques</h2>
        <p>EFT, branded cards and cheques are all essential tools when it comes to loyalty reward campaigns. We can manage and deliver all of these reward types, including processing and dispatch.</p>
      </div>

      <div class="clear"><!-- --></div>
    </article>
  </section>

  <!-- Content Gray -->
  <section class="container gray">
    <article class="content">
      <!-- Column Left -->
      <div class="column-left column">
        <h2>SMART Phone digital payments</h2>
        <p>We have just launched digital store cards with over 40 national retailers to choose from.</p>
        <p>As well as the traditional means of rewards and validation, is staying ahead of the curve and providing digital payment methods as an alternative to the production and delivery of cheques and gift cards. The benefits of digital payment methods include:</p>
        <ul>
          <li>Instant delivery</li>
          <li>Co-branded currency</li>
          <li>Strong retail partnerships</li>
          <li>Eliminate “lost in the mail” or physical delays</li>
          <li>No difficult customer activation process</li>
          <li>Can create any retailer partners digital program</li>
        </ul>
        <p>Digital currency is versatile and can be used for both competition rewards and all forms of promotional rebate.</p>
        <p>A recent example was one of our well known camera clients. They provided a Hoyts e-card to every customer who completed their online training document. The customer not only learn’t how to use their new camera they were rewarded with a gift for doing so. All online and fully automated.</p>
      </div>

      <!-- Column Right -->
      <div class="column-right column">
        <% if @is_au_site %>
          <img class="alignleft" src="cashbacks/images/currency-image-2.png" />
        <% else %>
          <img class="alignleft" src="cashbacks/images/currency-image-2-NZ.png" />
        <% end %>
      </div>

      <div class="clear"><!-- --></div>
    </article>
  </section>

  <%= render partial: "components/contact_us" %>

  <%= render partial: "components/footer", locals: {current_footer_parent: "current-menu-parent", footer_home_class: "", footer_cashback_promotions_class: "", footer_cashback_payments_and_distribution_class: "current-menu-item",
                                                      footer_loyalty_programs_class: "", footer_competitions_sweepstakes_and_games_class: "", footer_promotion_management_class: "",
                                                      footer_gift_with_purchase_class: "", footer_eftpos_cash_back_cards_class: "", footer_about_us_class: "", footer_register_class: "", footer_contact_class: ""} %>

</div>

app/views/cashbacks/competitions_sweepstakes_and_games.html.erb
<%= render partial: "components/header", locals: { current_menu_parent: "current-menu-parent", menu_home_class: "", menu_cashback_promotions_class: "", menu_cashback_payments_and_distribution_class: "", menu_loyalty_programs_class: "",
                                                    menu_competitions_sweepstakes_and_games_class: "current-menu-item", menu_promotion_management_class: "", menu_gift_with_purchase_class: "",
                                                    menu_eftpos_cash_back_cards_class: "", menu_about_us_class: "", menu_register_class: "", menu_contact_class: ""} %>

<!-- Page Banner -->
<section id="page-banner-container" style="background: transparent url(cashbacks/images/competitions-banner.jpg) no-repeat center center;">
  <article id="page-banner">
    <h1>Competitions, Sweepstakes and Games</h1>
    <h2>Efficient and effective consumer engagement</h2>
  </article>
</section>

<!-- Wrapper -->
<div id="wrapper">
  <!-- Content -->
  <section class="container">
    <article class="content">
      <!-- Column Left -->
      <div class="column-left column">
        <img src="cashbacks/images/competitions-image-1.jpg" />
      </div>

      <!-- Column Right -->
      <div class="column-right column">
        <p>An eye-catching competition, sweepstake or game can be one of the most effective ways of getting people talking about your brand.</p>
        <p>At the same time, with the right strategy in place it's possible to offer huge rewards to a customer for a tiny fraction of the perceived cost. By intelligently structuring prize pools and distribution, <%= @site_name %> can deliver standout campaigns without an excessive spend.</p>
      </div>

      <div class="clear"><!-- --></div>
    </article>
  </section>

  <!-- Content Gray -->
  <section class="container gray">
      <article class="content">
          <!-- Column Left -->
          <div class="column-left column">
              <h2>High-impact campaigns</h2>
              <p>There's nothing more exciting than offering customers potentially life changing rewards. With <%= @site_name %>, you can be guaranteed that you will see the very best return for this investment.</p>
          </div>

          <!-- Column Right -->
          <div class="column-right column">
              <img class="alignleft" src="cashbacks/images/competitions-image-2.png" />
          </div>

          <div class="clear"><!-- --></div>
      </article>
  </section>

  <!-- Content -->
  <section class="container">
    <article class="content">
      <!-- Column Left -->
      <div class="column-left column">
        <img class="alignright" src="cashbacks/images/competitions-image-3.png" />
      </div>

      <!-- Column Right -->
      <div class="column-right column">
        <h2>Cost-effective promotion</h2>
        <p>At the same time, with the right strategy in place it’s possible to offer huge rewards to accustomers for a tiny fraction of the perceived cost. By intelligently structuring prize pools and distribution, <%= @site_name %> can deliver standout campaigns without an excessive spend.</p>
      </div>

      <div class="clear"><!-- --></div>
    </article>
  </section>

  <!-- Content Background Image -->
  <section class="container image" style="background: transparent url(cashbacks/images/competitions-image-4.jpg) no-repeat center center;">
    <article class="content">

      <!-- Center -->
      <div class="center">
        <h2>From planning to distribution</h2>
        <p>Of course, any successful promotion campaign requires both thorough planning and effective delivery. Our end-to-end campaign management approach means you can rely on our expertise while freeing up valuable resources.</p>
      </div>

      <div class="clear"><!-- --></div>
    </article>
  </section>

  <%= render partial: "components/contact_us" %>

  <%= render partial: "components/footer", locals: {current_footer_parent: "current-menu-parent", footer_home_class: "", footer_cashback_promotions_class: "", footer_cashback_payments_and_distribution_class: "",
                                                      footer_loyalty_programs_class: "", footer_competitions_sweepstakes_and_games_class: "current-menu-item", footer_promotion_management_class: "",
                                                      footer_gift_with_purchase_class: "", footer_eftpos_cash_back_cards_class: "", footer_about_us_class: "", footer_register_class: "", footer_contact_class: ""} %>

</div>

app/views/cashbacks/contact.html.erb
<%= render partial: "components/header", locals: { current_menu_parent: "", menu_home_class: "", menu_cashback_promotions_class: "", menu_cashback_payments_and_distribution_class: "",menu_loyalty_programs_class: "",
                                                    menu_competitions_sweepstakes_and_games_class: "", menu_promotion_management_class: "", menu_gift_with_purchase_class: "",
                                                    menu_eftpos_cash_back_cards_class: "", menu_about_us_class: "", menu_contact_class: "current-menu-item"} %>

<!-- Wrapper -->
<div id="wrapper">
  <%= render partial: "components/contact_contact_us" %>

  <%= render partial: "components/footer", locals: {current_footer_parent: "", footer_home_class: "", footer_cashback_promotions_class: "", footer_cashback_payments_and_distribution_class: "",footer_loyalty_programs_class: "",
                                                      footer_competitions_sweepstakes_and_games_class: "", footer_promotion_management_class: "", footer_gift_with_purchase_class: "",
                                                      footer_eftpos_cash_back_cards_class: "", footer_about_us_class: "", footer_contact_class: "current-menu-item"} %>
</div>

app/views/cashbacks/eftpos_cash_back_cards.html.erb
<%= render partial: "components/header", locals: { current_menu_parent: "current-menu-parent", menu_home_class: "", menu_cashback_promotions_class: "", menu_cashback_payments_and_distribution_class: "", menu_loyalty_programs_class: "",
                                                    menu_competitions_sweepstakes_and_games_class: "", menu_promotion_management_class: "", menu_gift_with_purchase_class: "",
                                                    menu_eftpos_cash_back_cards_class: "current-menu-item", menu_about_us_class: "", menu_register_class: "", menu_contact_class: ""} %>

<!-- Page Banner -->
<section id="page-banner-container" style="background: transparent url(cashbacks/images/eftpos-banner.jpg) no-repeat center center;">
  <article id="page-banner">
    <h1>EFTPOS Cash Back Cards</h1>
    <h2>Industry-leading reward schemes and data collection</h2>
  </article>
</section>

<!-- Wrapper -->
<div id="wrapper">
  <!-- Content -->
  <section class="container">
    <article class="content no-padding">
      <!-- Column Left -->
      <div class="column-left column">
        <img class="alignright" src="cashbacks/images/eftpos-image-1.png" />
      </div>

      <!-- Column Right -->
      <div class="column-right column">
        <p>Branded EFTPOS cashback cards are a visually striking and cost-effective way of promotion. They offer the potential both to directly increase sales, as well as capturing data for future marketing opportunities.</p>
      </div>

      <div class="clear"><!-- --></div>
    </article>
  </section>


  <!-- Content Gray -->
  <section class="container gray">
    <article class="content">

      <!-- Column Left -->
      <div class="column-left column">
        <h2>Brand Recognition</h2>
        <p>Branded EFTPOS cards are a great way for your customers to choose their own reward, helping to build trust as well as the positive perception of your brand.</p>
        <p>Cards often stay in wallets and purses for months providing ongoing brand recognition and reminders. Designs can be changed quickly to keep messaging up to date and relevant.</p>
      </div>


      <!-- Column Right -->
      <div class="column-right column">
        <img class="alignleft" src="cashbacks/images/eftpos-image-2.png" />
      </div>

      <div class="clear"><!-- --></div>
    </article>
  </section>


  <!-- Content -->
  <section class="container">
    <article class="content">

      <!-- Column Left -->
      <div class="column-left column">
        <img class="absolute-left" src="cashbacks/images/eftpos-image-3.jpg" />
      </div>


      <!-- Column Right -->
      <div class="column-right column">
        <h2>Why outsource?</h2>
        <p>Reward campaigns can be time consuming and draining when it comes to resources. Instead, we can provide full-service EFTPOS Cash Back card solutions right through from the initial strategy to distribution and delivery. Along the way we’ll also handle data capture and insight, using the industry’s best technology.</p>
        <p>We can link the person who received the card to where they shop - by retailer, time date and how much they spend. Powerful data to use individually or aggregated into a data warehouse.</p>
      </div>

      <div class="clear"><!-- --></div>
    </article>
  </section>


  <!-- Content -->
  <section class="container">
    <article class="content">

      <!-- Column Left -->
      <div class="column-left column">
        <h2>Flexible solutions</h2>
        <p>With a wide range of options for digital platforms and delivery, our gift cards are more flexible than ever. While many customer appreciate a physical asset, new technology means there are new ways to offer your customers rewards, from text message to email – We’re always ahead of the curve.</p>
      </div>


      <!-- Column Right -->
      <div class="column-right column">
        <img class="alignleft" src="cashbacks/images/eftpos-image-4.png" />
      </div>

      <div class="clear"><!-- --></div>
    </article>
  </section>

  <%= render partial: "components/contact_us" %>

  <%= render partial: "components/footer", locals: {current_footer_parent: "current-menu-parent", footer_home_class: "", footer_cashback_promotions_class: "", footer_cashback_payments_and_distribution_class: "",
                                                      footer_loyalty_programs_class: "", footer_competitions_sweepstakes_and_games_class: "", footer_promotion_management_class: "",
                                                      footer_gift_with_purchase_class: "", footer_eftpos_cash_back_cards_class: "current-menu-item", footer_about_us_class: "", footer_register_class: "", footer_contact_class: ""} %>

</div>

app/views/cashbacks/home.html.erb
<%= render partial: "components/header", locals: { current_menu_parent: "", menu_home_class: "current-menu-item", menu_cashback_promotions_class: "", menu_cashback_payments_and_distribution_class: "",menu_loyalty_programs_class: "",
                                                    menu_competitions_sweepstakes_and_games_class: "", menu_promotion_management_class: "", menu_gift_with_purchase_class: "",
                                                    menu_eftpos_cash_back_cards_class: "", menu_about_us_class: "", menu_register_class: "", menu_contact_class: ""} %>

<!-- Banner -->
<section id="banner-container" style="background: transparent url(cashbacks/images/banner.jpg) no-repeat center center;">
  <article id="banner">
    <!-- Graphics -->
    <div class="graphics">
      <div class="inner">
        <img src="cashbacks/images/banner-graphics.png" />
      </div>
    </div>

    <!-- Banner Content -->
    <div id="banner-content">
      <h1>Cash Back programs for winning businesses</h1>
      <% if @is_au_site %>
        <p>Australia’s leading cashback and loyalty program specialist</p>
      <% else %>
        <p>New Zealand's leading cashback and loyalty program specialist</p>
      <% end %>
      <a href="#who-we-are-container" class="scrollDown">Learn more</a>
    </div>
  </article>
</section>


<!-- Wrapper -->
<div id="wrapper">
  <section id="clients-bar-container">
    <article id="clients-bar">
      <img src="cashbacks/images/canon-logo.png" />
      <img src="cashbacks/images/nikon-logo.png" />
      <img src="cashbacks/images/garmin-logo.png" />
      <img src="cashbacks/images/adobe-logo.png" />
      <img src="cashbacks/images/makita-logo.png" />
      <img src="cashbacks/images/imation-logo.png" />
      <img src="cashbacks/images/fujifilm-logo.png" />
      <img src="cashbacks/images/netgear-logo.png" />
    </article>
  </section>

  <!-- Who We Are -->
  <section id="who-we-are-container" class="home-content">
    <article id="who-we-are">
      <div class="left">
        <h2>Who we are</h2>
        <% if @is_au_site %>
          <p><%= ENV['CASHBACK_AU_SITE'] %> is Australia's leading cashback and loyalty program specialist.</p>
        <% else %>
          <p><%= ENV['CASHBACK_NZ_SITE'] %> is New Zealand's leading cashback and loyalty program specialist.</p>
        <% end %>
        <p>Our Cash Back gift card and promotion services are used by some of the world's most powerful brands across a wide range of industries, delivering outstanding sales results time and time again.</p>
      </div>

      <div class="right">
        <img src="cashbacks/images/who-we-are-image.png" />
      </div>

      <a href="#why-it-works-container" class="scrollDown">More</a>

      <div class="clear"></div>
    </article>
  </section>

  <!-- Why It Works -->
  <section id="why-it-works-container" class="home-content">
    <article id="why-it-works">
      <div class="left">
        <h2>Why it works</h2>
        <p>Did you know that almost half of all Australian and New Zealand consumers have a customer loyalty membership?</p>
        <p>Yet tapping into this market isn't just about sales. <br />With <%= ENV['CASHBACK_AU_SITE'] %> and <%= ENV['CASHBACK_NZ_SITE'] %> you'll have access to a wide range of data, including demographics, product performance and even opt-in email address, all of which can help grow your business even further.</p>
      </div>

      <div class="right">
        <img src="cashbacks/images/why-it-works-image.png" />
      </div>
      <div class="clear"></div>
    </article>
  </section>

  <!-- Solutions -->
  <section id="our-solutions-container">
    <article id="our-solutions">
      <h2>Our Solutions</h2>
      <div class="list">
        <div class="item">
          <a href="<%= cashback_promotions_path %>" class="thumb"><img src="cashbacks/images/solution-1-thumb.png" /></a>
          <h3><a href="<%= cashback_promotions_path %>">Cashback Promotions</a></h3>
          <p>Our promotion services are enormously flexible, covering EFTPOS Cash Back cards, EFT, cheques and digital gift cards.</p>
          <a href="<%= cashback_promotions_path %>" class="button">Find out more</a>
        </div>

        <div class="item">
          <a href="<%= loyalty_programs_path %>" class="thumb"><img src="cashbacks/images/solution-2-thumb.png" /></a>
          <h3><a href="<%= loyalty_programs_path %>">Gift cards and loyalty programs</a></h3>
          <p>Whether you're incentivising customers, staff or clients, branded EFTPOS gift cards are a visually striking and cost effective way to reach your goals.</p>
          <a href="<%= loyalty_programs_path %>" class="button">Find out more</a>
        </div>

        <div class="item">
          <a href="<%= gift_with_purchase_path %>" class="thumb"><img src="cashbacks/images/solution-3-thumb.png" /></a>
          <h3><a href="<%= gift_with_purchase_path %>">Gift With Purchase</a></h3>
          <p>Gift with purchase (or premium offer) programs take advantage of that feeling of getting something for nothing. It’s a memorable and effective technique that will make your customer feel special.</p>
          <a href="<%= gift_with_purchase_path %>" class="button">Find out more</a>
        </div>

        <div class="item">
          <a href="<%= competitions_sweepstakes_and_games_path %>" class="thumb"><img src="cashbacks/images/solution-4-thumb.png" /></a>
          <h3><a href="<%= competitions_sweepstakes_and_games_path %>">Contests, sweepstakes and games</a></h3>
          <p>Make shopping even more fun! Engage your customers with a wide range of competitions to give your loyalty programs a word-of-mouth boost.</p>
          <a href="<%= competitions_sweepstakes_and_games_path %>" class="button">Find out more</a>
        </div>

        <div class="clear"></div>
      </div>
    </article>
  </section>

  <%= render partial: "components/contact_us" %>

  <%= render partial: "components/footer", locals: {current_footer_parent: "", footer_home_class: "current-menu-item", footer_cashback_promotions_class: "", footer_cashback_payments_and_distribution_class: "",footer_loyalty_programs_class: "",
                                                      footer_competitions_sweepstakes_and_games_class: "", footer_promotion_management_class: "", footer_gift_with_purchase_class: "",
                                                      footer_eftpos_cash_back_cards_class: "", footer_about_us_class: "", footer_register_class: "", footer_contact_class: ""} %>
</div>

app/views/cashbacks/register.html.erb
<%= render partial: "components/header", locals: { current_menu_parent: "", menu_home_class: "", menu_cashback_promotions_class: "", menu_cashback_payments_and_distribution_class: "",menu_loyalty_programs_class: "",
                                                    menu_competitions_sweepstakes_and_games_class: "", menu_promotion_management_class: "", menu_gift_with_purchase_class: "",
                                                    menu_eftpos_cash_back_cards_class: "", menu_about_us_class: "", menu_register_class: "current-menu-item", menu_contact_class: ""} %>

<!-- Wrapper -->
<div id="wrapper">
  <%= render partial: "components/register" %>

  <%= render partial: "components/footer", locals: {current_footer_parent: "", footer_home_class: "", footer_cashback_promotions_class: "", footer_cashback_payments_and_distribution_class: "",footer_loyalty_programs_class: "",
                                                      footer_competitions_sweepstakes_and_games_class: "", footer_promotion_management_class: "", footer_gift_with_purchase_class: "",
                                                      footer_eftpos_cash_back_cards_class: "", footer_about_us_class: "", footer_register_class: "current-menu-item", footer_contact_class: ""} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <title></title>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/cashbacks.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="author" content="CashBack" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="apple-mobile-web-app-capable" content="yes" />

    <link rel="stylesheet" type="text/css" media="all" href="cashbacks/fonts/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" media="all" href="cashbacks/stylesheet/style.css" />

    <script type="text/javascript" src="cashbacks/javascript/jquery-1.12.2.min.js"></script>
    <script type="text/javascript" src="cashbacks/javascript/jquery-ui.min.js"></script>
    <script type="text/javascript" src="cashbacks/javascript/site.js"></script>

    <title>CashBack</title>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/prologic/home.html.erb
<%= render :template => "layouts/pro_logic" %>